name: mbharata_client
description: Flutter client for Mahabharata.pro with FreeDome interactive support
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_magento: ^2.1.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media & Graphics
  video_player: ^2.8.2
  chewie: ^1.7.4
  flutter_gl: ^0.0.4
  vector_math: ^2.1.4
  flutter_3d_controller: ^2.3.0
  
  # Audio & Sound
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  flutter_tts: ^3.8.5
  
  # FFI for native integration
  ffi: ^2.1.0
  
  # Dome & 3D Rendering
  
  # Sensors & Interaction
  sensors_plus: ^4.0.2
  device_info_plus: ^9.1.1
  permission_handler: ^11.1.0
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  archive: ^3.4.10
  
  # Development
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/models/
    - assets/textures/
    - files/
  
  fonts:
    - family: Sanskrit
      fonts:
        - asset: assets/fonts/Sanskrit-Regular.ttf
        - asset: assets/fonts/Sanskrit-Bold.ttf
          weight: 700
    - family: Devanagari
      fonts:
        - asset: assets/fonts/Devanagari-Regular.ttf
        - asset: assets/fonts/Devanagari-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
