tunnel: 5478d2d8-15f3-4950-bf23-4988152c9eba
credentials-file: /etc/cloudflared/5478d2d8-15f3-4950-bf23-4988152c9eba.json
metrics: 0.0.0.0:4901
loglevel: debug
logfile: /var/log/cloudflared.log
#region: us
ingress:
  - hostname: "hello-app.mbharata.com"
    service: hello_world
  - service: http://localhost:80


