tunnel: 9f2df57a-3b86-4e16-9ead-0c41dc127bf6
credentials-file: /etc/cloudflared/9f2df57a-3b86-4e16-9ead-0c41dc127bf6.json
metrics: 0.0.0.0:4903
loglevel: debug
logfile: /var/log/cloudflared-th.log
#region: th
ingress:
  - hostname: "hello-app-th.mbharata.com"
    service: hello_world
  - service: http://localhost:80


